---
- name: 'Check mandatory variables are defined'
  assert:
    that:
    - ttn_terminal_user is defined

- name: 'Check user exists'
  user:
    name: '{{ttn_terminal_user}}'
    state: present
  register: ttn_terminal_user_registered

- name: Install dependencies
  dnf:
    name: [zsh, git, vim, tmux]
    state: latest
  become: true

- name: Install starship
  shell: curl -fsSL https://starship.rs/install.sh | bash -s -- --force
  args:
    creates: /usr/local/bin/starship
  become: true

- name: switch to zsh
  user:
    name: '{{ttn_terminal_user}}'
    shell: /bin/zsh
  become: true

- name: Ensure .antigen.zsh
  copy:
    src: antigen.zsh
    dest: '{{ttn_terminal_user_registered.home}}/.antigen.zsh'
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644

- name: Ensure .zshrc
  copy:
    src: .zshrc
    dest: '{{ttn_terminal_user_registered.home}}/.zshrc'
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644

- name: Ensure .tmux.conf
  copy:
    src: .tmux.conf
    dest: '{{ttn_terminal_user_registered.home}}/.tmux.conf'
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644

- name: Ensure '{{ttn_terminal_user_registered.home}}/.config' dir exists
  file:
    path: '{{ttn_terminal_user_registered.home}}/.config'
    state: directory

- name: Ensure starship.toml
  template:
    src: starship.toml
    dest: '{{ttn_terminal_user_registered.home}}/.config/starship.toml'
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644
