---
- name: 'Check mandatory variables are defined'
  assert:
    that:
    - ttn_terminal_user is defined

- name: 'Check user exists'
  user:
    name: '{{ttn_terminal_user}}'
    state: present
  register: ttn_terminal_user_registered

- name: Install dependencies
  dnf:
    name: [zsh, git, vim, tmux]
    state: latest
  become: true

- name: Check that the space-prompt exists
  stat:
    path: /usr/local/bin/space-prompt
  register: space_prompt_exists

- name: "Download and Install space-prompt"
  block:
  - name: Download space-prompt aarch64
    get_url:
      url: https://github.com/thetechnick/go-space-prompt/releases/download/v0.1.0/space-prompt_linux_arm64.tar.gz
      dest: /tmp/space-prompt.tar.gz
    register: space_prompt_archive
    when: ansible_architecture == "aarch64"

  - name: Download space-prompt x86_64
    get_url:
      url: https://github.com/thetechnick/go-space-prompt/releases/download/v0.1.0/space-prompt_linux_amd64.tar.gz
      dest: /tmp/space-prompt.tar.gz
    register: space_prompt_archive
    when: ansible_architecture == "x86_64"

  - name: Install space-prompt
    unarchive:
      src: /tmp/space-prompt.tar.gz
      dest: /usr/local/bin
      remote_src: yes
    become: true
  when: not space_prompt_exists.stat.exists

- name: switch to zsh
  user:
    name: '{{ttn_terminal_user}}'
    shell: /bin/zsh
  become: true

- name: Ensure .antigen.zsh
  copy:
    src: antigen.zsh
    dest: '{{ttn_terminal_user_registered.home}}/.antigen.zsh'
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644

- name: Ensure .zshrc
  template:
    src: .zshrc
    dest: '{{ttn_terminal_user_registered.home}}/.zshrc'
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644

- name: Ensure .tmux.conf
  copy:
    src: .tmux.conf
    dest: '{{ttn_terminal_user_registered.home}}/.tmux.conf'
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644

- name: Ensure '{{ttn_terminal_user_registered.home}}/.config' dir exists
  file:
    path: '{{ttn_terminal_user_registered.home}}/.config'
    state: directory
