---
- name: 'Check mandatory variables are defined'
  assert:
    that:
    - ttn_terminal_user is defined

- name: Install dependencies
  dnf:
    name: '{{ item }}'
    state: latest
  with_items: [zsh, git, vim, tmux]
  become: true

- name: Install starship
  shell: curl -fsSL https://starship.rs/install.sh | bash -s -- --force
  args:
    creates: /usr/local/bin/starship
  become: true

- name: switch to zsh
  user:
    name: '{{ttn_terminal_user}}'
    shell: /bin/zsh
  become: true

- name: Ensure .antigen.zsh
  copy:
    src: antigen.zsh
    dest: /home/{{ttn_terminal_user}}/.antigen.zsh
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644

- name: Ensure .zshrc
  copy:
    src: .zshrc
    dest: /home/{{ttn_terminal_user}}/.zshrc
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644

- name: Ensure .tmux.conf
  copy:
    src: .tmux.conf
    dest: /home/{{ttn_terminal_user}}/.tmux.conf
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644

- name: Ensure starship.toml
  template:
    src: starship.toml
    dest: /home/{{ttn_terminal_user}}/.config/starship.toml
    owner: '{{ttn_terminal_user}}'
    group: '{{ttn_terminal_user}}'
    mode: 0644
