format = """
$username\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$env_var\
$crystal\
$cmd_duration\
$custom\
$line_break\
$jobs\
$battery\
$time\
$status\
$hostname\
$character"""

[hostname]
ssh_only=false
format='[ $hostname ](bg:black white)'

[golang]
symbol = 'Go '

[kubernetes]
disabled=false
style='blue bold'

[character]
success_symbol = '[✓ ](bold green bg:black)[ ](black bg:{{ttn_terminal_color}})[]({{ttn_terminal_color}})'
error_symbol = '[✗ ](bold red bg:black)[ ](black bg:{{ttn_terminal_color}})[]({{ttn_terminal_color}})'
